from pathlib import Path
import json,html
ROOT=Path(__file__).resolve().parents[1]
palette=json.loads((ROOT/'colors/tokens.json').read_text())['colors']
images=json.loads((ROOT/'images/manifest.json').read_text())
swatches=''
for k,c in palette.items():
    fg='#F4F1E9' if k in ['ink','graphite','leather'] else '#464643'
    swatches+=f'<div class="swatch"><div class="paint" style="background:{c["hex"]};color:{fg}"><span>{c["name"]}</span><code>{c["hex"]}</code></div><p>{c["role"]}</p></div>'
gallery=''
for i,item in enumerate(images):
    gallery+=f'''<figure class="asset"><a href="images/{item['web']}" aria-label="Open {item['title']}"><img loading="lazy" src="images/{item['thumbnail']}" alt="{html.escape(item['alt'])}" width="1536" height="1024"></a><figcaption><span class="eyebrow">0{i+1} / IMAGE STUDY</span><h3>{item['title']}</h3><p>{item['recommended_use']}</p><div class="downloads"><a href="images/{item['web']}" download>WebP ↓</a><a href="images/{item['master']}" download>PNG master ↓</a></div></figcaption></figure>'''
template='''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#464643"><title>Calibrated Co. — Brand field guide</title><link rel="icon" href="logos/svg/calibrated-favicon.svg"><link rel="stylesheet" href="fonts/fonts.css"><link rel="stylesheet" href="colors/tokens.css"><link rel="stylesheet" href="guide.css"></head>
<body><a class="skip" href="#identity">Skip to brand assets</a>
<header><a class="brand" href="#top"><img src="logos/svg/calibrated-horizontal-ink.svg" width="240" height="35" alt="Calibrated Co."></a><nav aria-label="Guide sections"><a href="#identity">Identity</a><a href="#type">Type</a><a href="#color">Color</a><a href="#images">Images</a></nav><span class="edition">FIELD GUIDE / 03</span></header>
<main id="top"><section class="hero"><div class="hero-copy"><span class="eyebrow">CALIBRATED CO. / BRAND SYSTEM</span><h1>The art<br>of better.</h1><p>Human marks.<br>Precise instruments.<br>Room to keep improving.</p><a class="button" href="README.md">Read the handoff guide ↗</a><span class="hero-foot">CRAFT × TECHNOLOGY / 2026</span></div><div class="hero-art"><img src="images/web/open-sketch.webp" alt="Open, overlapping graphite strokes gather into a flowing curve." width="1536" height="1024"><div class="hero-stamp"><img src="logos/svg/calibrated-mark-paper.svg" alt="" width="150" height="150"></div><span class="art-caption">01 — THE FIRST MARK</span></div></section>
<div class="intro"><p>A page to think on. A mark with conviction. Paper, graphite, steel and the warmth of a leather strap.</p><span class="eyebrow">IDENTITY / TYPE / COLOR<br>ARTWORK / MOTION / FILES</span></div>
<section id="identity" class="section"><div class="section-heading"><span class="eyebrow">01 / IDENTITY</span><h2>A little pressure.<br>A deliberate curve.</h2><p>The uneven, heavy C holds the craft. Its detached dash holds the technology. Keep both.</p></div>
<div class="logo-stage"><div class="mark-panel"><img src="logos/svg/calibrated-mark-paper.svg" alt="Calibrated asymmetric C mark" width="220" height="220"><span class="eyebrow">PRIMARY MARK</span></div><div class="word-panel"><img src="logos/svg/calibrated-wordmark-paper.svg" alt="CALIBRATED CO." width="1224" height="122"><p>The art of better.</p><span class="eyebrow">BOLD WORDMARK / ARCHIVO BLACK</span></div></div>
<div class="file-row"><div><strong>For a website header</strong><a href="logos/svg/calibrated-horizontal-ink.svg" download>Horizontal · SVG ↓</a><a href="logos/png/calibrated-horizontal-ink.png" download>Transparent PNG ↓</a></div><div><strong>For a hero or campaign</strong><a href="logos/svg/calibrated-wordmark-paper.svg" download>Paper wordmark · SVG ↓</a><a href="logos/svg/calibrated-signature-ink.svg" download>With tagline · SVG ↓</a></div><div><strong>For an icon or avatar</strong><a href="logos/svg/calibrated-mark-ink.svg" download>C mark · SVG ↓</a><a href="logos/png/calibrated-icon-512.png" download>App icon · PNG ↓</a></div></div>
<div class="logo-notes"><p><b>Leave room.</b> Add clear space of at least ¼ of the mark height. Use the mark alone below a 200px lockup.</p><p><b>Keep the weight.</b> Preserve the asymmetry and cut terminals. No thinning, perfect circles, shadows or chrome.</p><p><b>Use the right file.</b> The primary C is paper on charcoal. Leather brown is an accent only, never a logo background or logo color. All lettering is outlined.</p></div></section>
<section id="type" class="section"><div class="section-heading"><span class="eyebrow">02 / TYPOGRAPHY</span><h2>Quiet type.<br>A confident mark.</h2><p>The same regular face for headings, notes and reading. Monospace for code. Bold reserved for the identity.</p></div>
<div class="type-display"><div class="type-meta"><span class="eyebrow">IBM PLEX SANS / REGULAR 400</span><span>Headings, notes + reading</span></div><div class="specimen">Human marks.<br>Precise instruments.<br>Room to keep improving.</div><div class="alphabet">abcdefghijklmnopqrstuvwxyz<br>The everyday thought, clearly written. 0123456789</div><a href="fonts/ibmplexsans/IBMPlexSans[wdth,wght].ttf" download>Download the regular typeface ↓</a></div>
<div class="type-pair"><div><span class="eyebrow">IBM PLEX SANS / REGULAR 400</span><h3>Thought becomes a tool.</h3><p>Start with observation. Work through the uncertain parts. Test the result. Regular-weight text gives a longer thought room to breathe.</p><a href="fonts/ibmplexsans/IBMPlexSans[wdth,wght].ttf" download>Download variable desktop font ↓</a></div><div class="code-specimen"><span class="eyebrow">IBM PLEX MONO / REGULAR 400</span><pre><code>observe()
sketch = make(observation)
result = evaluate(sketch)
revise(result, human_judgment)</code></pre><p>Code, captions and instrument labels.</p><a href="fonts/ibmplexmono/IBMPlexMono-Regular.ttf" download>Download Mono Regular ↓</a></div></div>
<div class="reserved-mark"><img src="logos/svg/calibrated-wordmark-ink.svg" alt="CALIBRATED CO." width="1224" height="122"><div><span class="eyebrow">ARCHIVO BLACK / RESERVED FOR THE IDENTITY</span><p>The C and company name keep their weight. Use this voice sparingly, when something truly needs to stand out.</p><a href="fonts/archivoblack/ArchivoBlack-Regular.ttf" download>Download the wordmark font ↓</a></div></div>
<p class="small">All three families include OFL licenses. Six WOFF2 files and a ready-to-use <a href="fonts/fonts.css">local stylesheet</a> are bundled. Archivo Black's file weight is 400; its visual weight is already black.</p></section>
<section id="color" class="section"><div class="section-heading"><span class="eyebrow">03 / COLOR</span><h2>Paper, graphite<br>and leather.</h2><p>Soft charcoal, paper and graphite. A restrained leather brown supplies warmth beside the steel.</p></div><div class="palette">{{SWATCHES}}</div><div class="color-rules"><div><span class="eyebrow">THE EVERYDAY MIX</span><div class="ratio-bar"><i></i><i></i><i></i></div><p>Paper is the default. Charcoal and graphite carry the marks. Leather brown supplies a small, grounded accent; steel remains a material detail.</p></div><div><span class="eyebrow">READABLE COMBINATIONS</span><p>Charcoal or graphite on paper. Paper on charcoal. Paper on leather brown. Keep steel out of small text on a light background.</p><a href="colors/contrast.json">Contrast report ↗</a> <a href="colors/tokens.css" download>CSS tokens ↓</a> <a href="colors/tokens.json" download>JSON tokens ↓</a></div></div></section>
<section id="images" class="section"><div class="section-heading"><span class="eyebrow">04 / IMAGE LIBRARY</span><h2>Surfaces that<br>show the work.</h2><p>Five original generated studies, with full PNG masters and lighter WebP exports. Ready to use as illustrations throughout the website.</p></div><div class="gallery">{{GALLERY}}</div><div class="library-note"><p><b>Keep the source honest.</b> These are generated illustrations and material studies, not documentary photographs. Prompts, provenance, alt text and suggested uses are included.</p><a href="RIGHTS.md">Use & licensing ↗</a><a href="images/manifest.json">Asset manifest ↗</a><a href="images/prompts.json">Generation prompts ↗</a></div></section>
<section id="motion" class="motion-section"><div><span class="eyebrow">05 / MOTION</span><h2>From a mark<br>to a method.</h2><p>Graphite begins loose and uncontained. Continuous strokes gather, align and find syntax. A trace of the hand stays visible.</p><a class="button" href="motion/sketch-to-structure.html">Open the motion study ↗</a></div><div class="motion-preview"><img src="images/web/working-notation-768.webp" alt="Fine graphite working notation on off-white paper" width="1536" height="1024"><div><span>01 Sketch</span><span>02 Gather</span><span>03 Structure</span></div></div></section>
<section class="handoff"><span class="eyebrow">06 / HANDOFF</span><h2>Everything has<br>a working file.</h2><div><a href="Calibrated-Co-Design-Brief.pdf">Designer brief PDF ↗</a><a href="DESIGN-BRIEF.md">Editable design brief ↗</a><a href="README.md">Full brand guide ↗</a><a href="previews/identity-and-colors.png" download>Identity overview PNG ↓</a><a href="colors/palette.csv" download>Color values CSV ↓</a><a href="RIGHTS.md">Licenses & provenance ↗</a><a href="REFERENCES.md">Creative references ↗</a></div></section>
</main><footer><img src="logos/svg/calibrated-horizontal-ink.svg" alt="Calibrated Co." width="230" height="33"><span>THE ART OF BETTER.</span><span>BRAND KIT 3.0 / SEPTEMBER 2026</span></footer></body></html>'''
(ROOT/'index.html').write_text(template.replace('{{SWATCHES}}',swatches).replace('{{GALLERY}}',gallery))
print('Built portable visual guide.')

